#
# Copyright (c) 2021, 2023 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
micronaut:
  application:
    name: Catalog
  server:
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT15S
        descriptions: true
jackson:
  serialization-inclusion: ALWAYS
endpoints:
  prometheus:
    sensitive: false
tracing:
  jaeger:
    enabled: false
    sampler:
      probability: 1
    sender:
      agentHost: jaeger-agent
      agentPort: 5775
  zipkin:
    enabled: false
    sampler:
      probability: 1
    http:
      url: http://localhost:9411
      path:
    supportsJoin: false
coherence:
  topic:
    enabled: false
  proxy:
    enabled: false
  data:
    socks:
  tracing:
    ratio: -1
