#
# Copyright (c) 2021, 2025, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
micronaut:
  application:
    name: Users
  server:
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT15S
        descriptions: true
jackson:
  serialization-inclusion: ALWAYS
endpoints:
  prometheus:
    sensitive: false
coherence:
  topic:
    enabled: false
  proxy:
    enabled: false
  data:
    users:
  tracing:
    ratio: -1
otel:
  sdk:
    disabled: true
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://jaeger-inmemory-instance-collector:4317