#
# Copyright (c) 2021, 2025, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: carts
spec:
  cluster: SockShop
  role: Carts
  replicas: 1
  image: ghcr.io/oracle/coherence-micronaut-sockshop-carts:2.2.2-SNAPSHOT
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  env:
    - name: COHERENCE_SERVICE_NAME
      value: "Carts"
  application:
    main: com.oracle.coherence.examples.sockshop.micronaut.carts.Application
  jvm:
    memory:
      heapSize: 2g
    args:
      - "-Dotel.java.global-autoconfigure.enabled=true"
      - "-Dotel.service.name=carts"
      - "-Dotel.metrics.exporter=none"
      - "-Dotel.logs.exporter=none"
      - "-Dotel.exporter.otlp.traces.endpoint=http://jaeger-inmemory-instance-collector:4317"
      - "-Dotel.sdk.disabled=true"
      - "-Dcoherence.tracing.ratio=-1"
  coherence:
    metrics:
      enabled: true
  ports:
    - name: http
      port: 8080
      service:
        name: carts
        port: 80
      serviceMonitor:
        enabled: true
        path: /prometheus
    - name: metrics
      serviceMonitor:
        enabled: true
