#
# Copyright (c) 2021, 2025, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: shipping
spec:
  cluster: SockShop
  role: Shipping
  replicas: 1
  image: ghcr.io/oracle/coherence-micronaut-sockshop-shipping:2.3.1
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  env:
    - name: COHERENCE_SERVICE_NAME
      value: "Shipping"
  application:
    main: com.oracle.coherence.examples.sockshop.micronaut.shipping.Application
  jvm:
    memory:
      heapSize: 2g
  coherence:
    metrics:
      enabled: true
  ports:
    - name: http
      port: 8080
      service:
        name: shipping
        port: 80
      serviceMonitor:
        enabled: true
        path: /prometheus
    - name: metrics
      serviceMonitor:
        enabled: true
