name: CI Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        java-version: [ 17 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3.4.1
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}
    - name: Cache Maven packages
      uses: actions/cache@v3.0.6
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      env:
        MAVEN_OPTS: -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3
      run: mvn -B install --file pom.xml
    - name: Push container images
      env:
        REGISTRY_USER: ${{ github.actor }}
        REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $REGISTRY_PASSWORD | docker login ghcr.io -u $REGISTRY_USER --password-stdin
        mvn -B package --file pom.xml -Pcontainer -DskipTests
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-carts:latest
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-catalog:latest
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-orders:latest
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-payment:latest
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-shipping:latest
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-users:latest
      if: "github.event_name == 'push' && matrix.java-version == 11"
