name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Build
      env:
        MAVEN_OPTS: -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3
      run: mvn -B install --file pom.xml
    - name: Push container images
      env:
        REGISTRY_USER: ${{ github.actor }}
        REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF:11}
        echo $VERSION
        echo $REGISTRY_PASSWORD | docker login ghcr.io -u $REGISTRY_USER --password-stdin
        mvn -B package --file pom.xml -Pcontainer -DskipTests
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-carts:$VERSION
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-catalog:$VERSION
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-orders:$VERSION
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-payment:$VERSION
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-shipping:$VERSION
        docker push ghcr.io/oracle/coherence-micronaut-sockshop-users:$VERSION
